# Generated by Django 5.0.2 on 2024-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('head_office', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(help_text='Host url of smtp', verbose_name='host')),
                ('host_user', models.EmailField(help_text='Email address/host user of smtp', max_length=254, verbose_name='host user')),
                ('host_pass', models.TextField(help_text='Password of smtp', verbose_name='host password')),
                ('host_port', models.IntegerField(default=587, help_text='Host port of smtp', verbose_name='host port')),
                ('use_tls', models.BooleanField(default=True, help_text='Should tls be used for smtp', verbose_name='use tls')),
            ],
            options={
                'verbose_name': 'SMTP Setting',
            },
        ),
    ]
