# Generated by Django 5.0.2 on 2024-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cruise_api', '0002_remove_airline_logo_url_airline_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlineschedule',
            name='refundable',
            field=models.BooleanField(default=False),
        ),
    ]
