# Generated by Django 5.0.2 on 2024-02-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cruise_api', '0005_booking_booking_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking',
            new_name='transaction',
        ),
    ]
