# Generated by Django 5.0.2 on 2024-02-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cruise_api', '0006_rename_booking_booking_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airlineschedule',
            old_name='airline',
            new_name='airline_route',
        ),
    ]
