# Generated by Django 5.0.2 on 2024-03-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0002_airlineschedule_flight_class_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airlineschedule',
            name='flight_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FlightSupportBookingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified date')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('ticket_type', models.CharField(choices=[('Cancellation', 'Cancellation'), ('Close Date Reschedule', 'Close Date Reschedule'), ('Open Date Reschedule', 'Open Date Reschedule')], max_length=30)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('reschedule_date', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domestic_flights.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightSupportBookingTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified date')),
                ('details', models.CharField(max_length=200)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_flights.flightsupportbookingticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('passenger_title', models.CharField(blank=True, max_length=50, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domestic_flights.airlineschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveFlightInfoTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified date')),
                ('guid', models.CharField(max_length=90, unique=True)),
                ('flight_id', models.CharField(max_length=90, unique=True)),
                ('return_flight_id', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
