# Generated by Django 5.0.2 on 2024-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0004_billingaddress_transaction_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='airlineschedule',
            name='available_days',
            field=models.ManyToManyField(to='domestic_flights.weekdays'),
        ),
    ]
