# Generated by Django 5.0.2 on 2024-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0005_weekdays_airlineschedule_available_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekdays',
            options={'verbose_name_plural': 'Week days'},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
