# Generated by Django 5.0.2 on 2024-03-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0006_alter_weekdays_options_booking_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='passengerinfo',
            name='passenger_title',
        ),
    ]
