# Generated by Django 5.0.2 on 2024-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0007_remove_passengerinfo_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='contact_mobile',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
