# Generated by Django 5.0.2 on 2024-03-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0008_remove_transaction_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='full_name',
        ),
    ]
