# Generated by Django 5.0.2 on 2024-03-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0009_remove_passengerinfo_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinfo',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domestic_flights.booking'),
        ),
    ]
