# Generated by Django 5.0.2 on 2024-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0010_alter_passengerinfo_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='guid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
