# Generated by Django 5.0.2 on 2024-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0012_flightticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='for_date',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
