# Generated by Django 5.0.2 on 2024-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0014_alter_flightticket_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='airline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='flight_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
