# Generated by Django 5.0.2 on 2024-03-28 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_flights', '0016_rename_airline_flightticket_airline_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightticket',
            name='issued_date',
            field=models.DateField(default=datetime.date.today, max_length=50),
        ),
    ]
